import type { NextPage } from "next";
import { useSession, signIn, signOut } from "next-auth/react";
import Head from "next/head";
import PlaceCard from "../components/placecard";

const places = [{
  name: "UT Tower",
  location: "UT Austin Campus",
  image: "https://news.utexas.edu/wp-content/uploads/2020/06/Tower-through-trees-with-yellow-leaves-in-the-fall-20172360-1-scaled.jpg",
  rating: 4.5,
  description: "The UT Tower is a 307-foot (94 m) tall campanile and observation tower located on the campus of the University of Texas at Austin. It is the tallest structure in Austin and the second-tallest educational building in the United States.",
  comments: [
    {
      user: "John Doe",
      comment: "This is a great place to study!"
    },
    {
      user: "Jane Doe",
      comment: "I love this place!"
    }
  ]
}]

const Home: NextPage = () => {
  const { data: session } = useSession();
  console.log(session);
  function addNewPlace(placeInfo: any){
    places.push(placeInfo)
  }
        

  const bs = fetch("http://localhost:3001/location", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"
    },
    body: JSON.stringify({
      location: "UT Austin Campus",
      image: "https://news.utexas.edu/wp-content/uploads/2020/06/Tower-through-trees-with-yellow-leaves-in-the-fall-20172360-1-scaled.jpg",
      total_rating: 4.5,
      comments: {},
      category: "penis",
      x:1,
      y:2,
      count: 0
  })})

  const fs = fetch("http://localhost:3001/location?location=UT Austin Campus", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"
    },
  })
  console.log(fs)
  if (session) {
    return (
      <>
        <Head>
          <title>HackTX</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="h-screen w-screen p-8 bg-slate-800 text-white">
          <p className="text-right">
            <button onClick={() => signOut()}>Sign out</button>
          </p>
          <h1 className="bold text-center text-2xl font-bold">
            Hey {session?.user?.name}!
          </h1>
          <PlaceCard place={places[0]} />
        </div>
      </>
    );
  } else {
    return (
      <div className="flex h-screen w-screen flex-col items-center justify-center bg-slate-800 text-white">
        <p className="italic">
          Only @utexas.edu emails can be used to sign in.{" "}
        </p>
        <button
          className="bold flex flex-row items-center justify-center gap-10 rounded-2xl border-2 px-10 py-2 text-2xl hover:border-blue-400 hover:text-blue-400"
          onClick={() => signIn("google")}
        >
          <img src="/google.png" className="aspect-square w-14"></img>
          Sign In with Google
        </button>
      </div>
    );
  }
};

export default Home;